red_darker            = "#FFEBEE"                 
red_dark              = "#EF9A9A"               
red                   = "#EF5350"           
red_light             = "#E53935"                
red_lighter           = "#C62828"                  

pink_darker           = "#FCE4EC"                  
pink_dark             = "#F48FB1"                
pink                  = "#EC407A"           
pink_light            = "#D81B60"                 
pink_lighter          = "#AD1457"                   

purple_darker         = "#F3E5F5"                    
purple_dark           = "#CE93D8"                  
purple                = "#AB47BC"             
purple_light          = "#8E24AA"                   
purple_lighter        = "#6A1B9A"                     

deep_purple_darker    = "#EDE7F6"                         
deep_purple_dark      = "#B39DDB"                       
deep_purple           = "#7E57C2"                  
deep_purple_light     = "#5E35B1"                        
deep_purple_lighter   = "#4527A0"                          

indigo_darker         = "#E8EAF6"                    
indigo_dark           = "#9FA8DA"                  
indigo                = "#5C6BC0"             
indigo_light          = "#3949AB"                   
indigo_lighter        = "#283593"                     

blue_darker           = "#E3F2FD"                  
blue_dark             = "#90CAF9"                
blue                  = "#42A5F5"           
blue_light            = "#1E88E5"                 
blue_lighter          = "#1565C0"                   

light_blue_darker     = "#E1F5FE"                        
light_blue_dark       = "#81D4FA"                      
light_blue            = "#29B6F6"                  
light_blue_light      = "#039BE5"                       
light_blue_lighter    = "#0277BD"                         

cyan_darker           = "#E0F7FA"                  
cyan_dark             = "#80DEEA"                
cyan                  = "#26C6DA"           
cyan_light            = "#00ACC1"                 
cyan_lighter          = "#00838F"                   

teal_darker           = "#E0F2F1"                  
teal_dark             = "#80CBC4"                
teal                  = "#26A69A"           
teal_light            = "#00897B"                 
teal_lighter          = "#00695C"                   

green_darker          = "#E8F5E9"                   
green_dark            = "#A5D6A7"                 
green                 = "#66BB6A"
green_light           = "#43A047"                  
green_lighter         = "#2E7D32"                    

light_green_darker    = "#F1F8E9"                         
light_green_dark      = "#C5E1A5"                       
light_green           = "#9CCC65"                  
light_green_light     = "#7CB342"                        
light_green_lighter   = "#558B2F"                          

lime_darker           = "#F9FBE7"                  
lime_dark             = "#E6EE9C"                
lime                  = "#D4E157"           
lime_light            = "#C0CA33"                 
lime_lighter          = "#9E9D24"                   

yellow_darker         = "#FFFDE7"                    
yellow_dark           = "#FFF59D"                  
yellow                = "#FFEE58"             
yellow_light          = "#FDD835"                   
yellow_lighter        = "#F9A825"                     

amber_darker          = "#FFF8E1"                   
amber_dark            = "#FFE082"                 
amber                 = "#FFCA28"
amber_light           = "#FFB300"                  
amber_lighter         = "#FF8F00"                    

orange_darker         = "#FFF3E0"                    
orange_dark           = "#FFCC80"                  
orange                = "#FFA726"             
orange_light          = "#FB8C00"                   
orange_lighter        = "#EF6C00"                     

salmon_darker         = "#FBE9E7"                         
salmon_dark           = "#FFAB91"                       
salmon                = "#FF7043"                  
salmon_light          = "#F4511E"                        
salmon_lighter        = "#D84315"                          

brown_darker          = "#EFEBE9"                   
brown_dark            = "#BCAAA4"                 
brown                 = "#8D6E63"
brown_light           = "#6D4C41"                  
brown_lighter         = "#4E342E"                    

grey_darker           = "#FAFAFA"                  
grey_dark             = "#EEEEEE"                
grey                  = "#BDBDBD"           
grey_light            = "#757575"                 
grey_lighter          = "#424242"                   

blue_grey_darker     = "#ECEFF1"                        
blue_grey_dark       = "#B0BEC5"                      
blue_grey             = "#78909C"                  
blue_grey_light      = "#546E7A"                       
blue_grey_lighter    = "#37474F"                         


black                 = "#000000"
white                 = "#FFFFFF"

